#!/usr/bin/env python3
"""Generate random Ising instances on Pegasus or Zephyr graphs.

The ``--size`` argument is passed directly to ``dwave_networkx`` graph
constructors: ``pegasus_graph(size)`` or ``zephyr_graph(size)``.

Instances are generated by sampling random QUBO coefficients uniformly in
[-1, 1] on node diagonals and native graph edges, then converting to Ising.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

import dwave_networkx as dnx
import dimod
import h5py
import networkx as nx
import numpy as np


IDEAL_TARGET_SIZES = {
    "pegasus": 16,
    "zephyr": 20,
}

LIVE_SOLVERS = {
    "pegasus": "Advantage_system6.4",
    "zephyr": "Advantage2_system1.12",
}


@dataclass(frozen=True)
class TargetGraph:
    graph: nx.Graph
    topology_type: str
    size: int | None
    source: str


@dataclass(frozen=True)
class MappingResult:
    mapping: dict[int, int]
    missing_spins: int
    missing_couplers: int

    @property
    def is_complete(self) -> bool:
        return self.missing_spins == 0 and self.missing_couplers == 0


def positive_int(value: str) -> int:
    parsed = int(value)
    if parsed <= 0:
        raise argparse.ArgumentTypeError("value must be > 0")
    return parsed


def fmt_value(value: float) -> str:
    return f"{value:.6f}".rstrip("0").rstrip(".")


def build_source_graph(topology: str, size: int) -> nx.Graph:
    if topology == "pegasus":
        return dnx.pegasus_graph(size)
    if topology == "zephyr":
        return dnx.zephyr_graph(size)
    raise ValueError(f"unsupported topology: {topology}")


def topology_label(topology: str) -> str:
    return "P" if topology == "pegasus" else "Z"


def extract_topology_size(topology_shape: object) -> int | None:
    if isinstance(topology_shape, (list, tuple)) and topology_shape:
        try:
            return int(topology_shape[0])
        except (TypeError, ValueError):
            return None
    return None


def build_target_graph(topology: str, use_live_qpu: bool) -> TargetGraph:
    if use_live_qpu:
        try:
            from dwave.system import DWaveSampler

            sampler = DWaveSampler(solver=LIVE_SOLVERS[topology])
            target = sampler.to_networkx_graph()
            topo = sampler.properties.get("topology", {})
            topo_type = str(topo.get("type", topology))
            topo_size = extract_topology_size(topo.get("shape"))
            return TargetGraph(target, topo_type, topo_size, "live-qpu")
        except Exception as exc:
            print(
                "Warning: live QPU graph unavailable "
                f"({exc}); using ideal {topology} graph instead."
            )

    size = IDEAL_TARGET_SIZES[topology]
    return TargetGraph(build_source_graph(topology, size), topology, size, "ideal")


def generate_qubo_terms(
    graph: nx.Graph,
    rng: np.random.Generator,
) -> dict[tuple[int, int], float]:
    qubo: dict[tuple[int, int], float] = {}

    for node in graph.nodes:
        qubo[(node, node)] = float(rng.uniform(-1.0, 1.0))

    for u, v in graph.edges:
        key = (u, v) if u < v else (v, u)
        qubo[key] = float(rng.uniform(-1.0, 1.0))

    return qubo


def qubo_to_ising_terms(
    qubo: dict[tuple[int, int], float],
) -> tuple[dict[int, float], dict[tuple[int, int], float]]:
    h_raw, j_raw, _offset = dimod.qubo_to_ising(qubo)
    h = {int(node): float(value) for node, value in h_raw.items()}

    j_terms: dict[tuple[int, int], float] = {}
    for (u, v), value in j_raw.items():
        key = (int(u), int(v)) if u < v else (int(v), int(u))
        j_terms[key] = float(value)

    return h, j_terms


def regular_index(nodes: list[int]) -> dict[int, int]:
    return {node: idx + 1 for idx, node in enumerate(sorted(nodes))}


def evaluate_mapping(
    source_graph: nx.Graph,
    target_graph: nx.Graph,
    mapping: dict[int, int],
) -> MappingResult:
    valid_nodes = {node for node in source_graph.nodes if mapping.get(node) in target_graph.nodes}
    missing_couplers = 0

    for u, v in source_graph.edges:
        if u not in valid_nodes or v not in valid_nodes:
            missing_couplers += 1
            continue
        mapped_u = mapping[u]
        mapped_v = mapping[v]
        if not target_graph.has_edge(mapped_u, mapped_v):
            missing_couplers += 1

    return MappingResult(
        mapping=mapping,
        missing_spins=source_graph.number_of_nodes() - len(valid_nodes),
        missing_couplers=missing_couplers,
    )


def sublattice_mappings(topology: str) -> Callable[[nx.Graph, nx.Graph], object]:
    if topology == "pegasus":
        return dnx.pegasus_sublattice_mappings
    if topology == "zephyr":
        return dnx.zephyr_sublattice_mappings
    raise ValueError(f"unsupported topology: {topology}")


def find_complete_mapping(
    topology: str,
    source_graph: nx.Graph,
    target: TargetGraph,
) -> MappingResult | None:
    map_iter = sublattice_mappings(topology)(source_graph, target.graph)
    best: MappingResult | None = None

    for map_fn in map_iter:
        candidate = {node: map_fn(node) for node in source_graph.nodes}
        result = evaluate_mapping(source_graph, target.graph, candidate)
        if result.is_complete:
            return result
        if (
            best is None
            or result.missing_spins < best.missing_spins
            or (
                result.missing_spins == best.missing_spins
                and result.missing_couplers < best.missing_couplers
            )
        ):
            best = result

    return best


def h5_coupling_coo(
    nodes: list[int],
    j_terms: dict[tuple[int, int], float],
    index: dict[int, int],
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    entries: list[tuple[int, int, float]] = []

    for node in nodes:
        idx = index[node]
        entries.append((idx, idx, 0.0))

    for (u, v), value in j_terms.items():
        idx_u = index[u]
        idx_v = index[v]
        entries.append((idx_u, idx_v, value))
        entries.append((idx_v, idx_u, value))

    entries.sort(key=lambda item: (item[1], item[0]))
    rows = np.array([row for row, _, _ in entries], dtype=np.int64)
    cols = np.array([col for _, col, _ in entries], dtype=np.int64)
    vals = np.array([value for _, _, value in entries], dtype=np.float64)
    return rows, cols, vals


def write_txt(
    path: Path,
    nodes: list[int],
    h: dict[int, float],
    j_terms: dict[tuple[int, int], float],
    index: dict[int, int],
    label: str,
) -> None:
    header = "QPU coordinates" if label == "qpu" else "regular 1-based coordinates"
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        handle.write(f"# i j value ({header})\n")
        for node in sorted(nodes):
            idx = index[node]
            handle.write(f"{idx} {idx} {fmt_value(h[node])}\n")
        for u, v in sorted(j_terms, key=lambda edge: (index[edge[0]], index[edge[1]])):
            handle.write(f"{index[u]} {index[v]} {fmt_value(j_terms[(u, v)])}\n")


def write_h5(
    path: Path,
    nodes: list[int],
    h: dict[int, float],
    j_terms: dict[tuple[int, int], float],
    index: dict[int, int],
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    min_index = min(index.values()) if index else 1
    max_index = max(index.values()) if index else 0
    index_offset = 1 if min_index >= 1 else 0
    biases = np.zeros(max_index + 1 - index_offset, dtype=np.float64)
    for node in nodes:
        biases[index[node] - index_offset] = h[node]
    rows, cols, vals = h5_coupling_coo(nodes, j_terms, index)
    with h5py.File(path, "w") as handle:
        ising = handle.create_group("Ising")
        ising.create_dataset("biases", data=biases)
        j_coo = ising.create_group("J_coo")
        j_coo.create_dataset("I", data=rows)
        j_coo.create_dataset("J", data=cols)
        j_coo.create_dataset("V", data=vals)


def write_instance(
    output_dir: Path,
    prefix: str,
    coord_name: str,
    formats: set[str],
    nodes: list[int],
    h: dict[int, float],
    j_terms: dict[tuple[int, int], float],
    index: dict[int, int],
) -> list[Path]:
    written: list[Path] = []
    stem = f"{prefix}_{coord_name}"
    if "txt" in formats:
        path = output_dir / f"{stem}.txt"
        write_txt(path, nodes, h, j_terms, index, coord_name)
        written.append(path)
    if "h5" in formats:
        path = output_dir / f"{stem}.h5"
        write_h5(path, nodes, h, j_terms, index)
        written.append(path)
    return written


def requested_formats(value: str) -> set[str]:
    return {"txt", "h5"} if value == "both" else {value}


def requested_coords(value: str) -> set[str]:
    return {"linear", "qpu"} if value == "both" else {value}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate random Ising instances on Pegasus or Zephyr graphs by "
            "sampling random QUBO coefficients and converting to Ising."
        )
    )
    parser.add_argument("--topology", choices=("pegasus", "zephyr"), required=True)
    parser.add_argument("--size", type=positive_int, required=True)
    parser.add_argument("--instances", type=positive_int, default=1)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--coords", choices=("linear", "qpu", "both"), default="both")
    parser.add_argument("--format", choices=("txt", "h5", "both"), default="both")
    parser.add_argument("--seed", type=int, default=1234)
    parser.add_argument(
        "--use-live-qpu",
        action="store_true",
        help="Use the live QPU graph for QPU-coordinate output when available.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    source_graph = build_source_graph(args.topology, args.size)
    if source_graph.number_of_nodes() == 0:
        raise ValueError(f"{args.topology} graph with size {args.size} is empty")

    formats = requested_formats(args.format)
    coords = requested_coords(args.coords)
    label = topology_label(args.topology)
    target: TargetGraph | None = None
    mapping_result: MappingResult | None = None
    qpu_available = False

    if "qpu" in coords:
        target = build_target_graph(args.topology, args.use_live_qpu)
        if target.topology_type != args.topology:
            print(
                "Warning: requested "
                f"{args.topology} QPU coordinates, but target graph reports "
                f"{target.topology_type}; skipping QPU output."
            )
        elif target.size is not None and args.size > target.size:
            print(
                "Warning: requested "
                f"{args.topology} size {args.size}, but {target.source} target "
                f"supports size {target.size}; writing linear output only."
            )
        else:
            mapping_result = find_complete_mapping(args.topology, source_graph, target)
            if mapping_result is not None and mapping_result.is_complete:
                qpu_available = True
            else:
                missing_spins = mapping_result.missing_spins if mapping_result else source_graph.number_of_nodes()
                missing_couplers = mapping_result.missing_couplers if mapping_result else source_graph.number_of_edges()
                print(
                    "Warning: requested graph cannot be completely represented on "
                    f"the {target.source} target graph "
                    f"(missing_spins={missing_spins}, missing_couplers={missing_couplers}); "
                    "writing linear output only."
                )

    if coords == {"qpu"} and not qpu_available:
        coords = {"linear"}
    elif "qpu" in coords and not qpu_available:
        coords.discard("qpu")

    source_nodes = list(source_graph.nodes)
    linear_index = regular_index(source_nodes)

    total_written = 0
    print(
        f"Generating {args.instances} {args.topology} instance(s), "
        f"{label}{args.size}, |V|={source_graph.number_of_nodes()}, "
        f"|E|={source_graph.number_of_edges()}"
    )

    for instance_id in range(1, args.instances + 1):
        rng = np.random.default_rng(args.seed + args.size * 100000 + instance_id)
        qubo = generate_qubo_terms(source_graph, rng)
        h, j_terms = qubo_to_ising_terms(qubo)
        prefix = f"random_ising_{args.topology}_{label}{args.size}_inst{instance_id}"

        if "linear" in coords:
            written = write_instance(
                args.output_dir,
                prefix,
                "linear",
                formats,
                source_nodes,
                h,
                j_terms,
                linear_index,
            )
            total_written += len(written)

        if "qpu" in coords:
            assert mapping_result is not None
            qpu_index = {node: int(mapping_result.mapping[node]) for node in source_nodes}
            written = write_instance(
                args.output_dir,
                prefix,
                "qpu",
                formats,
                source_nodes,
                h,
                j_terms,
                qpu_index,
            )
            total_written += len(written)

    print(f"Done. Wrote {total_written} file(s) to {args.output_dir}")


if __name__ == "__main__":
    main()
